[package]
name = "rust_for_embedded_systems"
version = "0.1.0"
edition = "2021"

[dependencies]
cortex-m = { version = "0.7.7", features = ["inline-asm"] }
cortex-m-rt = "0.7.5"
cortex-m-semihosting = "0.5.0"
